# Generated by Django 5.0.8 on 2024-08-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_alter_booking_options_alter_booking_checkin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
    ]
